/*
 Generated by typeshare 1.13.2
*/

export type ContentNode = 
	| { type: "media", body: IContentMedia }
	| { type: "list", body: IContentList };

export interface IContentList {
	id: string;
	title: string;
	description?: string;
	items: ContentNode[];
}

export interface IContentMedia {
	name: string;
	path: string;
	duration: number;
	thumbnailPath?: string;
	mediaType: number;
	createdAt: string;
	isLocal: boolean;
	size?: string;
}

export interface IContentProviderViews {
	main: string;
	search?: string;
}

export interface IContentProvider {
	key: string;
	name: string;
	views: IContentProviderViews;
}

export enum ContentProviderViewKey {
	Main = "main",
	Search = "search",
}

export enum MediaType {
	Video = "Video",
	Audio = "Audio",
}

